export type ClaimType = {
	id?: number;
	claim_number?: number;
	individual_member: number;
	provider: number;

	place_of_service_description: string;
	place_of_service_code: string;
	billing_provider_npi: string;
	attending_provider_name_npi_specialty_code: string;

	other_provider_npi_ids: string;
	admission_date: string;
	admission_hour: {
		hour: string;
		period?: "AM" | "PM";
	};
	source_of_admission: string;
	type_of_admission_visit: string;
	admitting_diagnosis: string;
	patient_reason_for_visit: string;

	diagnosis_date?: string;
	diagnosis_code?: string;
	diagnosis_category: string;
	diagnosis_source: string;
	diagnosis_description: string;
	principal_procedure_code: string;

	other_diagnosis_codes_poc_code: string;
	external_cause_of_injury_code: string;
	treatment_authorization_codes: string;

	lonic_category: string;
	lonic_code: string;
	lonic_description: string;

	cpt_code: string;
	cpt_category: string;
	cpt_description: string;

	service_start_date: string;
	service_end_date: string;
	discharge_hour: {
		hour: string;
		period?: "AM" | "PM";
	};
	type_of_bill: string;
	payer_name: string;
	revenue_code_tin_number: string;

	service_charge: number;
	additional_charge: number;
	non_covered_charge?: number;

	release_of_information_receipt: File[];
	receipts: File[];
	medication_prescription: File[];
	medical_imaging?: File[];
	exam_and_lab?: File[];

	// for details
	patient_control_number?: string;
	member_payment_amount?: string;
	total_amount_payment_by_insurance?: string;
	grand_total?: string;
	total_payment_for_provider_after_discount?: string;
	patient_discharge_status?: string;
	additional_notes?: string;
};

export type ClaimdetailType = {
	id: number;
	claim_number: string;
	billing_provider_npi: string;
	diagnosis_date: string;
	diagnosis_code: string;
	diagnosis_category: string;
	diagnosis_description: string;
	non_covered_charge: string | null;
	other_diagnosis_codes_poc_code: string | null;
	admitting_diagnosis: string;
	patient_discharge_status: string;
	claim_status: string;
	attending_provider_npi: string;
	attending_provider_name: string;
	attending_provider_tin_number: string;
	refferal_provider_name: string | null;
	refferal_provider_npi: string | null;
	refferal_provider_tin_number: string | null;
	service_start_date: string;
	service_end_date: string;
	patient_control_number: string | null;
	additional_charge: number;
	member_payment_amount: string;
	total_amount_payment_by_insurance: string;
	grand_total: string;
	total_payment_for_provider_after_discount: string;
	place_of_service_code: number;
	place_of_service_description: string;
	admission_date: string;
	discharge_hour: { hour: string; period: string };
	admission_hour: { hour: string; period: string };
	treatment_authorization_codes: string;
	additional_notes: string;
	source_of_admission: string;
	type_of_admission_visit: string;
	patient_reason_for_visit: string;
	diagnosis_source: string;
	receipts: string;
	medication_prescription: string | null;
	medical_imaging: string | null;
	exam_and_lab: string | null;
	cpt_code: string;
	cpt_category: string;
	cpt_description: string;
	external_cause_of_injury_code: string;
	principal_procedure_code: string;
	other_procedure_code_description: string | null;
	operating_physician_name_npi_specialty_code: string | null;
	type_of_bill: string;
	payer_name: string;
	release_of_information_receipt: string | null;
	service_charge: string;
	revenue_code_tin_number: string;
	lonic_code: string;
	lonic_description: string;
	created_at: string;
	user: {
		id: number;
		email: string;
		phone_number: string | null;
		first_name: string;
		middle_name: string | null;
		last_name: string;
		date_of_birth: string | null;
		gender: string | null;
		date_joined: string;
		last_login: string;
		is_active: boolean;
		role: string;
		provider: number;
	};
	individual_member: {
		id: number;
		member_id: string;
		family_id: string;
		personal_representative_id: string;
		plan_cycle: string;
		first_name: string;
		last_name: string;
		middle_name: string;
		amharic_first_name: string;
		amharic_last_name: string;
		amharic_middle_name: string;
		gender: string;
		insurance_type: string;
		has_transport_subscription: boolean;
		date_of_birth: string;
		marital_status: string;
		member_organization_type: string;
		benefit_plan: string;
		member_payment_duty: number;
		member_type: string;
		member_status: string;
		phone_number: string;
		email_address: string;
		mailing_address_line1: string;
		country: string;
		street_address_line_1: string;
		street_address_line_2: string;
		city: string;
		region: string;
		kifle_ketema: string;
		representative_first_name: string;
		representative_last_name: string;
		representative_middle_name: string;
		representative_gender: string;
		representative_date_of_birth: string;
		representative_marital_status: string;
		representative_mailing_address_line1: string;
		representative_country: string;
		representative_street_address_line_1: string;
		representative_street_address_line_2: string;
		representative_city: string;
		representative_region: string;
		representative_kifle_ketema: string;
		representative_phone_number: string;
		representative_email_address: string;
		relationship_to_member: string;
		is_representative: boolean;
		height: number;
		weight: number;
		tin_number: string;
		max_out_of_pocket: number;
		max_out_of_pocket_etb: number;
		first_payment: string;
		total_medical_expense: string | null;
		deductible_type: string;
		deductible: number;
		payment_date: string;
		benefit_begin_date: string;
		payment_status: boolean;
		paid_by: string;
		amount_paid_by_member: number;
		duty_stage: string;
		dependent_of: number;
	};
	provider: {
		id: number;
		provider_npi_id: string | null;
		tin_number: string;
		provider_place_of_work: string;
		provider_last_name: string;
		provider_first_name: string;
		provider_middle_initial: string;
		provider_date_of_birth: string;
		provider_last_name_amharic: string;
		provider_first_name_amharic: string;
		provider_middle_initial_amharic: string;
		provider_title: string;
		provider_contact_person: string;
		provider_contact_email: string;
		provider_contact_phone_number: string;
		provider_discount_agreement: number;
		provider_health_tier: string;
		provider_health_sub_tier: string;
		institute_name: string;
		provider_service_type: string;
		provider_gender: string;
		street_address_line_1: string | null;
		street_address_line_2: string | null;
		provider_city: string;
		provider_county: string | null;
		provider_region: string;
		provider_kifle_ketema: string;
		provider_zip_code: string;
		provider_phone_number: string;
		provider_fax: string;
		provider_email: string;
		provider_type: string;
		provider_primary_specialty: string;
		provider_sub_specialty: string;
		provider_group_email: string | null;
		medicare_provider_number: string | null;
		provider_group_name: string;
		provider_group_contact_person: string;
		provider_group_phone_number: string;
		provider_group_address_line_1: string | null;
		provider_group_address_line_2: string | null;
	};
};
