import { type GridColDef } from "@mui/x-data-grid";

export const reportColumns: GridColDef[] = [
	{
		field: "id",
		headerName: "ID",
		width: 100,
		sortable: true,
		filterable: true,
	},
	{
		field: "claim_number",
		headerName: "Claim Number",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "billing_provider_npi",
		headerName: "Billing Provider NPI",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "diagnosis_date",
		headerName: "Diagnosis Date",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "diagnosis_code",
		headerName: "Diagnosis Code",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "diagnosis_category",
		headerName: "Diagnosis Category",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "diagnosis_description",
		headerName: "Diagnosis Description",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "non_covered_charge",
		headerName: "Non-Covered Charge",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "other_diagnosis_codes_poc_code",
		headerName: "Other Diagnosis Codes POC Code",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "admitting_diagnosis",
		headerName: "Admitting Diagnosis",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "patient_discharge_status",
		headerName: "Patient Discharge Status",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "claim_status",
		headerName: "Claim Status",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "attending_provider_npi",
		headerName: "Attending Provider NPI",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "attending_provider_name",
		headerName: "Attending Provider Name",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "attending_provider_tin_number",
		headerName: "Attending Provider TIN",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "refferal_provider_name",
		headerName: "Referral Provider Name",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "refferal_provider_npi",
		headerName: "Referral Provider NPI",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "refferal_provider_tin_number",
		headerName: "Referral Provider TIN",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "service_start_date",
		headerName: "Service Start Date",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "service_end_date",
		headerName: "Service End Date",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "patient_control_number",
		headerName: "Patient Control Number",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "additional_charge",
		headerName: "Additional Charge",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "member_payment_amount",
		headerName: "Member Payment Amount",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "total_amount_payment_by_insurance",
		headerName: "Total Payment by Insurance",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "grand_total",
		headerName: "Grand Total",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "total_payment_for_provider_after_discount",
		headerName: "Total Payment for Provider After Discount",
		width: 300,
		sortable: true,
		filterable: true,
	},
	{
		field: "place_of_service_code",
		headerName: "Place of Service Code",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "place_of_service_description",
		headerName: "Place of Service Description",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "admission_date",
		headerName: "Admission Date",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "discharge_hour.hour",
		headerName: "Discharge Hour",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "discharge_hour.period",
		headerName: "Discharge Period",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "admission_hour.hour",
		headerName: "Admission Hour",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "admission_hour.period",
		headerName: "Admission Period",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "treatment_authorization_codes",
		headerName: "Treatment Authorization Codes",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "additional_notes",
		headerName: "Additional Notes",
		width: 300,
		sortable: true,
		filterable: true,
	},
	{
		field: "source_of_admission",
		headerName: "Source of Admission",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "type_of_admission_visit",
		headerName: "Type of Admission Visit",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "patient_reason_for_visit",
		headerName: "Reason for Visit",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "diagnosis_source",
		headerName: "Diagnosis Source",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "receipts",
		headerName: "Receipts",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "medication_prescription",
		headerName: "Medication Prescription",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "medical_imaging",
		headerName: "Medical Imaging",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "exam_and_lab",
		headerName: "Exam and Lab",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "cpt_code",
		headerName: "CPT Code",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "cpt_category",
		headerName: "CPT Category",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "cpt_description",
		headerName: "CPT Description",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "external_cause_of_injury_code",
		headerName: "External Cause of Injury Code",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "principal_procedure_code",
		headerName: "Principal Procedure Code",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "other_procedure_code_description",
		headerName: "Other Procedure Code Description",
		width: 300,
		sortable: true,
		filterable: true,
	},
	{
		field: "operating_physician_name_npi_specialty_code",
		headerName: "Operating Physician NPI/Specialty Code",
		width: 300,
		sortable: true,
		filterable: true,
	},
	{
		field: "type_of_bill",
		headerName: "Type of Bill",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "payer_name",
		headerName: "Payer Name",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "service_charge",
		headerName: "Service Charge",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "revenue_code_tin_number",
		headerName: "Revenue Code TIN",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "lonic_code",
		headerName: "LONIC Code",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "lonic_description",
		headerName: "LONIC Description",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "created_at",
		headerName: "Created At",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.member_id",
		headerName: "Member ID",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.family_id",
		headerName: "Family ID",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.personal_representative_id",
		headerName: "Representative ID",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.plan_cycle",
		headerName: "Plan Cycle",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.first_name",
		headerName: "First Name",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.last_name",
		headerName: "Last Name",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "individual_member.middle_name",
		headerName: "Middle Name",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.amharic_first_name",
		headerName: "First Name (Amharic)",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.amharic_last_name",
		headerName: "Last Name (Amharic)",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.amharic_middle_name",
		headerName: "Middle Name (Amharic)",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.gender",
		headerName: "Gender",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "individual_member.insurance_type",
		headerName: "Insurance Type",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.has_transport_subscription",
		headerName: "Transport Subscription",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.date_of_birth",
		headerName: "Date of Birth",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.marital_status",
		headerName: "Marital Status",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.member_organization_type",
		headerName: "Organization Type",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.benefit_plan",
		headerName: "Benefit Plan",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.member_payment_duty",
		headerName: "Payment Duty",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.member_type",
		headerName: "Member Type",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.member_status",
		headerName: "Member Status",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.phone_number",
		headerName: "Phone Number",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.email_address",
		headerName: "Email Address",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.mailing_address_line1",
		headerName: "Mailing Address Line 1",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.country",
		headerName: "Country",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "individual_member.street_address_line_1",
		headerName: "Street Address Line 1",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.street_address_line_2",
		headerName: "Street Address Line 2",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.city",
		headerName: "City",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "individual_member.region",
		headerName: "Region",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "individual_member.kifle_ketema",
		headerName: "Kifle Ketema",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_first_name",
		headerName: "Representative First Name",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_last_name",
		headerName: "Representative Last Name",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_middle_name",
		headerName: "Representative Middle Name",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_gender",
		headerName: "Representative Gender",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_date_of_birth",
		headerName: "Representative Date of Birth",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_marital_status",
		headerName: "Representative Marital Status",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_mailing_address_line1",
		headerName: "Representative Mailing Address Line 1",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_country",
		headerName: "Representative Country",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_street_address_line_1",
		headerName: "Representative Street Address Line 1",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_street_address_line_2",
		headerName: "Representative Street Address Line 2",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_city",
		headerName: "Representative City",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_region",
		headerName: "Representative Region",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_kifle_ketema",
		headerName: "Representative Kifle Ketema",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_phone_number",
		headerName: "Representative Phone Number",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.representative_email_address",
		headerName: "Representative Email Address",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.relationship_to_member",
		headerName: "Relationship to Member",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.is_representative",
		headerName: "Is Representative",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.height",
		headerName: "Height",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "individual_member.weight",
		headerName: "Weight",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "individual_member.tin_number",
		headerName: "TIN Number",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.max_out_of_pocket",
		headerName: "Max Out of Pocket",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.max_out_of_pocket_etb",
		headerName: "Max Out of Pocket (ETB)",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.first_payment",
		headerName: "First Payment",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.total_medical_expense",
		headerName: "Total Medical Expense",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.deductible_type",
		headerName: "Deductible Type",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.deductible",
		headerName: "Deductible",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.payment_date",
		headerName: "Payment Date",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.benefit_begin_date",
		headerName: "Benefit Begin Date",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.payment_status",
		headerName: "Payment Status",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.paid_by",
		headerName: "Paid By",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "individual_member.amount_paid_by_member",
		headerName: "Amount Paid by Member",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.duty_stage",
		headerName: "Duty Stage",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "individual_member.dependent_of",
		headerName: "Dependent Of",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "user.email",
		headerName: "User Email",
		width: 250,
		sortable: true,
		filterable: true,
	},

	{
		field: "user.phone_number",
		headerName: "User Phone Number",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "user.first_name",
		headerName: "User First Name",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "user.last_name",
		headerName: "User Last Name",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_npi_id",
		headerName: "Provider NPI ID",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.individual_member.last_name",
		headerName: "Member Last Name",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.individual_member.first_name",
		headerName: "Member First Name",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.individual_member.gender",
		headerName: "Member Gender",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.tin_number",
		headerName: "TIN Number",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_place_of_work",
		headerName: "Place of Work",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_last_name",
		headerName: "Last Name",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_first_name",
		headerName: "First Name",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_middle_initial",
		headerName: "Middle Initial",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_date_of_birth",
		headerName: "Date of Birth",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_last_name_amharic",
		headerName: "Last Name (Amharic)",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_first_name_amharic",
		headerName: "First Name (Amharic)",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_middle_initial_amharic",
		headerName: "Middle Initial (Amharic)",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_title",
		headerName: "Title",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_contact_person",
		headerName: "Contact Person",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_contact_email",
		headerName: "Contact Email",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_contact_phone_number",
		headerName: "Contact Phone Number",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_discount_agreement",
		headerName: "Discount Agreement",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_health_tier",
		headerName: "Health Tier",
		width: 150,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_health_sub_tier",
		headerName: "Health Sub-Tier",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.institute_name",
		headerName: "Institute Name",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_service_type",
		headerName: "Service Type",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_gender",
		headerName: "Gender",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.street_address_line_1",
		headerName: "Address Line 1",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.street_address_line_2",
		headerName: "Address Line 2",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_city",
		headerName: "City",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_county",
		headerName: "County",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_region",
		headerName: "Region",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_kifle_ketema",
		headerName: "Kifle Ketema",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_zip_code",
		headerName: "Zip Code",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_phone_number",
		headerName: "Phone Number",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_fax",
		headerName: "Fax",
		width: 150,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_email",
		headerName: "Email",
		width: 250,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_type",
		headerName: "Provider Type",
		width: 200,
		sortable: true,
		filterable: true,
	},

	{
		field: "provider.provider_primary_specialty",
		headerName: "Primary Specialty",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_sub_specialty",
		headerName: "Sub Specialty",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_group_email",
		headerName: "Group Email",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.medicare_provider_number",
		headerName: "Medicare Provider Number",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_group_name",
		headerName: "Group Name",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_group_contact_person",
		headerName: "Group Contact Person",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_group_phone_number",
		headerName: "Group Phone Number",
		width: 200,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_group_address_line_1",
		headerName: "Group Address Line 1",
		width: 250,
		sortable: true,
		filterable: true,
	},
	{
		field: "provider.provider_group_address_line_2",
		headerName: "Group Address Line 2",
		width: 250,
		sortable: true,
		filterable: true,
	},
];
